config/routes.rb
Rails.application.routes.draw do


  get '/shop' => 'storefront#index'

  get '/about' => 'storefront#about'

  devise_for :users
  namespace :admin do
    resources :products
    resources :brands
    resources :categories
  end

  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create]
  resources :orders, only: [:new, :create, :show, :index]

  root 'storefront#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Goosebaggin</a>
    </div>
    <!-- Navebar Links -->
    <%= render 'layouts/navbar_links' %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class='dropdown'>
          <a href="#" class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
          Shop<span class='caret'></span>
          </a>
          <ul class='dropdown-menu' role='menu'>
            <% Category.all.each do |cat| %>
              <li><%= link_to cat.name.capitalize, shop_path(cat_id: cat.id) %></li>
            <% end %>
            <li class='divider'></li>
            <li><%= link_to "All Products", shop_path %></li>
          </ul>
        </li>

          <li><%= link_to 'About',about_path %></li>

      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Backroom <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Brands", admin_brands_path %></li>
            <li><%= link_to "Categories", admin_categories_path %></li>
            <li><%= link_to "Products", admin_products_path %></li>
          </ul>
        </li>
      <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">
      <!-- Search form -->
      <div class= "pull-left">
        <%= form_tag(shop_path, method: :get, role: "search", class: "form-inline") do %>
          <div class="form-group">
            <%= text_field_tag(:search, nil, placeholder: "Search Products", class: "form-control input-sm") %>
          </div>
          <%= submit_tag("Search", class: "btn btn-default btn-sm") %>
        <% end %>
           <div class="pull-left">
              <li><%= link_to fa_icon('shopping-cart', text: "Your Cart", class: "btn btn-success"), edit_cart_path %></li>
          </div>

      </div>
        <% if user_signed_in? %>
        <!-- Accounts -->
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <!-- Log Out -->
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <!-- Sign In -->
        <li><%= link_to 'Login', new_user_session_path %></li>
        <!-- Register -->
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merchant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <% if notice.present? %>
    <div class="alert alert-info alert-dismissable"><%= flash.now[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>